#!/usr/bin/env python3
"""
Give each privacy policy page a distinct <title>, description, canonical and
readable typography.

They're generated by App Privacy Policy Generator, which emits an identical
"Privacy Policy" title and no meta for every app — five near-identical pages
competing with each other in search. The body copy is left untouched; this
only rewrites the <head>.

    python3 tools/patch-policy-heads.py
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# file -> (app name, indexable)
PAGES = {
    "CARD_CRUSH_PRIVACY_POLICY.html": ("Card Crush: Match Suits", True),
    "CROSSWORD_PRIVACY_POLICY.html": ("Crossword: Word Puzzles", True),
    "KITTY_PRIVACY_POLICY.html": ("Kitty: Card Showdown", True),
    "TAP_REGRET_PRIVACY_POLICY.html": ("Tap & Regret: ZigZag Run", True),
    # Retired app, kept only so any old store listing doesn't 404.
    "DMD_PRIVACY_POLICY.html": ("Drag Me Down", False),
}

STYLE = (
    "<style>"
    "body{font-family:'Nunito',-apple-system,'Segoe UI',Helvetica,Arial,sans-serif;"
    "max-width:44rem;margin:0 auto;padding:2em 1.25em 4em;line-height:1.65;"
    "color:#211a36;background:#fff7f0}"
    "strong{display:block;margin-top:1.8em;font-size:1.05rem}"
    "a{color:#ff5a36}"
    "hr{border:none;border-top:1px solid rgba(33,26,54,.12);margin:2.5em 0 1.5em}"
    ".back{display:inline-block;margin-bottom:1.5em;font-weight:700;"
    "text-decoration:none;color:#ff5a36}"
    "</style>"
)


def head_block(app, filename, indexable):
    robots = "index, follow" if indexable else "noindex, follow"
    return (
        f"<title>Privacy Policy — {app} | GiloByte</title>\n"
        f'      <meta name="description" content="Privacy policy for the '
        f'{app} Android app by GiloByte.">\n'
        f'      <meta name="robots" content="{robots}">\n'
        f'      <link rel="canonical" href="https://gilobyte.com/{filename}">\n'
        f'      <link rel="icon" href="/favicon.ico" sizes="32x32">\n'
        f'      <meta name="theme-color" content="#fff7f0">\n'
        f'      <link rel="preconnect" href="https://fonts.googleapis.com">\n'
        f'      <link href="https://fonts.googleapis.com/css2?family=Nunito:'
        f'wght@400;700&display=swap" rel="stylesheet">\n'
        f"      {STYLE}"
    )


def main():
    for filename, (app, indexable) in PAGES.items():
        path = os.path.join(ROOT, filename)
        if not os.path.exists(path):
            print(f"skip (missing): {filename}")
            continue

        html = open(path, encoding="utf-8").read()
        original = html

        # Replace the generic title + the generator's single style rule.
        html = re.sub(
            r"<title>\s*Privacy Policy\s*</title>",
            head_block(app, filename, indexable),
            html,
            count=1,
        )
        html = re.sub(
            r"<style>\s*body\s*\{[^}]*\}\s*</style>",
            "",
            html,
            count=1,
        )

        # A way back to the site — these pages are dead ends otherwise.
        if 'class="back"' not in html:
            html = re.sub(
                r"(<body>)",
                r'\1\n    <a class="back" href="/">← GiloByte</a>',
                html,
                count=1,
            )

        if html == original:
            print(f"no change: {filename}  (pattern not matched — check by hand)")
        else:
            open(path, "w", encoding="utf-8").write(html)
            print(f"patched:   {filename}  →  {app}"
                  f"{'' if indexable else '  [noindex: retired app]'}")


if __name__ == "__main__":
    main()
